// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2p_5s1Douvf0nph2DEujVMuff-2RfCIk',
    appId: '1:445079146163:web:6ee0c886408536c07beac6',
    messagingSenderId: '445079146163',
    projectId: 'wealtai-inexor',
    authDomain: 'wealtai-inexor.firebaseapp.com',
    storageBucket: 'wealtai-inexor.firebasestorage.app',
    measurementId: 'G-2CSDXYDRN8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIrFGKNfeFbJZP-Xx3DDh8uTC3rIxomR0',
    appId: '1:445079146163:android:5a3b4a1de0c163227beac6',
    messagingSenderId: '445079146163',
    projectId: 'wealtai-inexor',
    storageBucket: 'wealtai-inexor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQF5ys0ySmP2WYAxyX6AxnqRGVfqoEI5o',
    appId: '1:445079146163:ios:27ae13b8d8b1f1c17beac6',
    messagingSenderId: '445079146163',
    projectId: 'wealtai-inexor',
    storageBucket: 'wealtai-inexor.firebasestorage.app',
    androidClientId: '445079146163-0nhflb0p1665houlm3tvij3jh81jc743.apps.googleusercontent.com',
    iosClientId: '445079146163-gql5gdkonqnsn1o17avhlp9tctv8teru.apps.googleusercontent.com',
    iosBundleId: 'com.inexor.wealthnx.aiapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQF5ys0ySmP2WYAxyX6AxnqRGVfqoEI5o',
    appId: '1:445079146163:ios:a27ecec7f68bec397beac6',
    messagingSenderId: '445079146163',
    projectId: 'wealtai-inexor',
    storageBucket: 'wealtai-inexor.firebasestorage.app',
    androidClientId: '445079146163-0nhflb0p1665houlm3tvij3jh81jc743.apps.googleusercontent.com',
    iosClientId: '445079146163-feohnam35m8sju76v24uhdme5jr91ur8.apps.googleusercontent.com',
    iosBundleId: 'com.inexor.wealthnx.ai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2p_5s1Douvf0nph2DEujVMuff-2RfCIk',
    appId: '1:445079146163:web:80c3af549ae0d4747beac6',
    messagingSenderId: '445079146163',
    projectId: 'wealtai-inexor',
    authDomain: 'wealtai-inexor.firebaseapp.com',
    storageBucket: 'wealtai-inexor.firebasestorage.app',
    measurementId: 'G-ZH26B1T527',
  );

}